name: Pedagio Automático

on:
  schedule:
    - cron: '*/30 * * * *' # Roda a cada 30 minutos
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  rodar-pedagio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Instalar Dependências
        run: pip install pandas supabase python-dotenv

      - name: Executar Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python script_validacao.py